function handles=StartUpFcnKarta(handles)
uipanelwidth=0.98;
uipanelheight=0.94;
uipanelx=0.01;
uipanely=0.01;
togglebwidth=0.1;
togglebheight=0.05;
fonttype.buttons=handles.preferences.fonttype.buttons;
fonttype.subpanel=handles.preferences.fonttype.subpanel;
fonttype.axes=handles.preferences.fonttype.axes;
fonttype.text=handles.preferences.fonttype.text;
fontsize.buttons=handles.preferences.fontsize.buttons;
fontsize.subpanel=handles.preferences.fontsize.subpanel;
fontsize.axes=handles.preferences.fontsize.axes;
fontsize.text=handles.preferences.fontsize.text;
dx1=0.45;dy1=0.58;
dx2=0.43;dy2=0.2;
dx3=0.48;dy3=0.08;dy03=0.01;dy13=0;
dx4=0.48;dy4=0.6;
dx5=0.58;dy5=0.1;dx51=0.38;
dx6=0.92;dy6=0.35;
dx7=0.2;dy7=0.06;
%||-----------------------uipkarta-------------------------------------
set(handles.uipkarta,'Units','normalized','Position',[uipanelx,uipanely,uipanelwidth,uipanelheight]);
set(handles.uipkarta,'BackgroundColor',handles.preferences.color.panel);
set(handles.uipkarta,'Title','Карта','TitlePosition','righttop');
set(handles.uipkarta,'FontName',fonttype.subpanel,'FontSize',fontsize.subpanel);
%|||----------------------tbkarta--------------------------------
set(handles.tbkarta,'BackgroundColor',handles.preferences.color.tabs(1,:));
set(handles.tbkarta,'Units','normalized','Position',[0.41,0.95,togglebwidth,togglebheight]);
set(handles.tbkarta,'String','Карта');
set(handles.tbkarta,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
%|||----------------------uiptipzadachi-------------------------------
set(handles.uiptipzadachi,'Units','normalized','Position',[0.01,0.87,0.29,0.12]);
set(handles.uiptipzadachi,'BackgroundColor',handles.preferences.color.subpanel);
set(handles.uiptipzadachi,'Title','Решаемая задача');
set(handles.uiptipzadachi,'FontName',fonttype.subpanel,'FontSize',fontsize.subpanel);
%||||----------------------Elements-----------------------------------
set(handles.tzadacha,'Units','normalized','Position',[0.2,0.5,0.6,0.1]);
set(handles.tzadacha,'String','Тип решаемой задачи','HorizontalAlignment','left');
set(handles.tzadacha,'FontName',fonttype.text,'FontSize',fontsize.text,'Visible','off');
set(handles.pbMod,'Units','normalized','Position',[0.05,0.2,dx1,dy1]);
set(handles.pbMod,'String','Моделирование');
set(handles.pbMod,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.pbIngAn,'Units','normalized','Position',[0.05+dx1,0.2,dx1,dy1]);
set(handles.pbIngAn,'String','Анализ');
set(handles.pbIngAn,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
%|||----------------------uipkrtklconfig------------------------------
set(handles.uipkrtklconfig,'Units','normalized','Position',[0.01,0.01,0.29,0.85]);
set(handles.uipkrtklconfig,'BackgroundColor',handles.preferences.color.subpanel);
set(handles.uipkrtklconfig,'Title','Настройка кластера');
set(handles.uipkrtklconfig,'FontName',fonttype.subpanel,'FontSize',fontsize.subpanel);
set(handles.axkrtklon,'Units','normalized','Position',[0.04,0.5,dx6,dy6]);
set(handles.axkrtklon,'FontName',fonttype.axes,'FontSize',fontsize.axes);
set(handles.axkrtklon,'XTickLabel',[],'YTickLabel',[]);
set(handles.pbkrtonall,'Units','normalized','Position',[0.04,0.86,dx7,dy7]);
set(handles.pbkrtonall,'String','Вкл. все');
set(handles.pbkrtonall,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.pbkrtoffall,'Units','normalized','Position',[0.05+dx7,0.86,dx7,dy7]);
set(handles.pbkrtoffall,'String','Выкл. все');
set(handles.pbkrtoffall,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.tkrtklon,'Units','normalized','Position',[0.04,0.93,dx6,0.05]);
set(handles.tkrtklon,'String','Включить/выключить облучатель','HorizontalAlignment','center');
set(handles.tkrtklon,'FontName',fonttype.text,'FontSize',fontsize.text);
%axes(handles.axdnklon);
%box on;
set(handles.axkrtklpol,'Units','normalized','Position',[0.04,0.04,dx6,dy6]);
set(handles.axkrtklpol,'FontName',fonttype.axes,'FontSize',fontsize.axes);
set(handles.axkrtklpol,'XTickLabel',[],'YTickLabel',[]);
set(handles.tkrtklpol,'Units','normalized','Position',[0.04,0.4,dx6,0.05]);
set(handles.tkrtklpol,'String','Настройка поляризации','HorizontalAlignment','center');
set(handles.tkrtklpol,'FontName',fonttype.text,'FontSize',fontsize.text);
%axes(handles.axdnklon);
%box on;
%|||----------------------uipkrt--------------------------------------
set(handles.uipkrt,'Units','normalized','Position',[0.31,0.3,0.68,0.69]);
set(handles.uipkrt,'BackgroundColor',handles.preferences.color.subpanel);
set(handles.uipkrt,'Title','Результаты расчета');
set(handles.uipkrt,'FontName',fonttype.subpanel,'FontSize',fontsize.subpanel);
set(handles.axkrt,'Units','normalized','Position',[0.045,0.08,0.91,0.89]);
set(handles.axkrt,'FontName',fonttype.axes,'FontSize',fontsize.axes);
set(handles.axkrt,'XLim',[-180,180],'YLim',[-90,90],'YTick',[-90 -60 -30 0 30 60 90]);
set(handles.axkrt,'XTick',[-180 -150 -120 -90 -60 -30 0 30 60 90 120 150 180]);
set(handles.axkrt,'YTickLabel',{'-90';'-60';'-30';'0';'30';'60';'90'});
set(handles.axkrt,'XTickLabel',{'-180';'-150';'-120';'-90';'-60';'-30';'0';'30';'60';'90';'120';'150';'180'});
set(handles.axkrt,'XGrid','on','YGrid','on','Box','on');
%|||----------------------uipkrtparnav------------------------------
set(handles.uipkrtparnav,'Units','normalized','Position',[0.31,0.01,0.32,0.28]);
set(handles.uipkrtparnav,'BackgroundColor',handles.preferences.color.subpanel);
set(handles.uipkrtparnav,'Title','Параметры наведения');
set(handles.uipkrtparnav,'FontName',fonttype.subpanel,'FontSize',fontsize.subpanel);
set(handles.tLevel,'Units','normalized','Position',[0.02,0.85,dx5,dy5]);
set(handles.tLevel,'String','Уровень сечения ДН, дБ','HorizontalAlignment','left');
set(handles.tLevel,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.tmuka,'Units','normalized','Position',[0.02,0.7,dx5,dy5]);
set(handles.tmuka,'String','Подспутниковая точка, град','HorizontalAlignment','left');
set(handles.tmuka,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.edLevel,'Units','normalized','Position',[0.6,0.85,dx51,dy5],'String','');
set(handles.edLevel,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.edmuka,'Units','normalized','Position',[0.6,0.7,dx51,dy5],'String','');
set(handles.edmuka,'FontName',fonttype.text,'FontSize',fontsize.text);
%||||----------------------Analiz_elements---------------------------
set(handles.uipkrtcelfcn,'Units','normalized','Position',[0.02,0.05,dx4,dy4]);
set(handles.uipkrtcelfcn,'BackgroundColor',handles.preferences.color.subpanel);
set(handles.uipkrtcelfcn,'Title','Целевая функция');
set(handles.uipkrtcelfcn,'FontName',fonttype.subpanel,'FontSize',fontsize.subpanel);
set(handles.uipkrtalgfcn,'Units','normalized','Position',[0.5,0.05,dx4,dy4]);
set(handles.uipkrtalgfcn,'BackgroundColor',handles.preferences.color.subpanel);
set(handles.uipkrtalgfcn,'Title','Алгоритм расчета');
set(handles.uipkrtalgfcn,'FontName',fonttype.subpanel,'FontSize',fontsize.subpanel);
set(handles.rbmaxPP,'Units','normalized','Position',[0.04,0.7,0.95,0.2]);
set(handles.rbmaxPP,'String','Полезной мощности');
set(handles.rbmaxPP,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.rbmaxPS,'Units','normalized','Position',[0.04,0.5,0.95,0.2]);
set(handles.rbmaxPS,'String','Пропускной способности');
set(handles.rbmaxPS,'FontName',fonttype.buttons,'FontSize',fontsize.buttons,'Visible','off');
set(handles.rbconturSKO,'Units','normalized','Position',[0.04,0.7,0.95,0.2]);
set(handles.rbconturSKO,'String','СКО контура');
set(handles.rbconturSKO,'FontName',fonttype.buttons,'FontSize',fontsize.buttons,'Visible','off');
set(handles.rbpik,'Units','normalized','Position',[0.04,0.7,0.95,0.2]);
set(handles.rbpik,'String','Пиковый');
set(handles.rbpik,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.rbgrad,'Units','normalized','Position',[0.04,0.5,0.95,0.2]);
set(handles.rbgrad,'String','Градиентный');
set(handles.rbgrad,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.rbpikgrad,'Units','normalized','Position',[0.04,0.3,0.95,0.2]);
set(handles.rbpikgrad,'String','Пиково-градиентный');
set(handles.rbpikgrad,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.rbsolve,'Units','normalized','Position',[0.04,0.1,0.95,0.2]);
set(handles.rbsolve,'String','Обращение к ВКМ');
set(handles.rbsolve,'FontName',fonttype.buttons,'FontSize',fontsize.buttons,'Visible','off');
%||||----------------------Model_elements---------------------------
set(handles.tmupr,'Units','normalized','Position',[0.02,0.55,dx5,dy5]);
set(handles.tmupr,'String','Долгота точки прицеливания, град','HorizontalAlignment','left');
set(handles.tmupr,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.tthpr,'Units','normalized','Position',[0.02,0.4,dx5,dy5]);
set(handles.tthpr,'String','Широта точки прицеливания, град','HorizontalAlignment','left');
set(handles.tthpr,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.tsigma,'Units','normalized','Position',[0.02,0.25,dx5,dy5]);
set(handles.tsigma,'String','Угол поворота антенны, град','HorizontalAlignment','left');
set(handles.tsigma,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.edmupr,'Units','normalized','Position',[0.6,0.55,dx51,dy5],'String','');
set(handles.edmupr,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.edthpr,'Units','normalized','Position',[0.6,0.4,dx51,dy5],'String','');
set(handles.edthpr,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.edsigma,'Units','normalized','Position',[0.6,0.25,dx51,dy5],'String','');
set(handles.edsigma,'FontName',fonttype.text,'FontSize',fontsize.text);
%|||----------------------uipkrtparotobr------------------------------
set(handles.uipkrtparotobr,'Units','normalized','Position',[0.64,0.01,0.35,0.28]);
set(handles.uipkrtparotobr,'BackgroundColor',handles.preferences.color.subpanel);
set(handles.uipkrtparotobr,'Title','Параметры отображения расчета');
set(handles.uipkrtparotobr,'FontName',fonttype.subpanel,'FontSize',fontsize.subpanel);
%||||----------------------Elements-----------------------------------
set(handles.pbkrtstart,'Units','normalized','Position',[0.53,0.05,dx2,dy2]);
set(handles.pbkrtstart,'String','Рассчитать');
set(handles.pbkrtstart,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.pbkrtkontur,'Units','normalized','Position',[0.53,2*0.05+dy2,dx2,dy2]);
set(handles.pbkrtkontur,'String','Задать контур');
set(handles.pbkrtkontur,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.pbkrtSSS,'Units','normalized','Position',[0.04,0.05,dx2,dy2]);
set(handles.pbkrtSSS,'String','Данные о ССС');
set(handles.pbkrtSSS,'FontName',fonttype.buttons,'FontSize',fontsize.buttons,'Visible','off');
set(handles.pbkrtclear,'Units','normalized','Position',[0.53,3*0.05+2*dy2,dx2,dy2]);
set(handles.pbkrtclear,'String','Очистить');
set(handles.pbkrtclear,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.pbkrtProstr,'Units','normalized','Position',[0.53,4*0.05+3*dy2,dx2,dy2]);
set(handles.pbkrtProstr,'String','Проекция Globe');
set(handles.pbkrtProstr,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.uipkrttype,'Units','normalized','Position',[0.53,3*0.05+2*dy2,dx2,0.4]);
set(handles.uipkrttype,'BackgroundColor',handles.preferences.color.subpanel);
set(handles.uipkrttype,'Title','Проекция карты');
set(handles.uipkrttype,'FontName',fonttype.subpanel,'FontSize',fontsize.subpanel,'Visible','off');
set(handles.rborto,'Units','normalized','Position',[0.08,0.6,0.9,0.25]);
set(handles.rborto,'String','Прямоугольная');
set(handles.rborto,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.rbglobe,'Units','normalized','Position',[0.08,0.2,0.9,0.25]);
set(handles.rbglobe,'String','Globe');
set(handles.rbglobe,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.chbZone,'Units','normalized','Position',[0.04,1-dy3-dy13,dx3,dy3]);
set(handles.chbZone,'String','Зона видимости спутника');
set(handles.chbZone,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.chbAuto,'Units','normalized','Position',[0.04,1-2*dy3-dy03-dy13,dx3,dy3]);
set(handles.chbAuto,'String','Автоматический перерасчет');
set(handles.chbAuto,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.chbNum,'Units','normalized','Position',[0.04,1-3*dy3-2*dy03-dy13,dx3,dy3]);
set(handles.chbNum,'String','Номера и Ga');
set(handles.chbNum,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.chbGa,'Units','normalized','Position',[0.04,1-4*dy3-3*dy03-dy13,dx3,dy3]);
set(handles.chbGa,'String','Отображать Ga');
set(handles.chbGa,'FontName',fonttype.buttons,'FontSize',fontsize.buttons,'Visible','off');
set(handles.chbfill,'Units','normalized','Position',[0.04,1-4*dy3-3*dy03-dy13,dx3,dy3]);
set(handles.chbfill,'String','Заполнение контура');
set(handles.chbfill,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.chblabel,'Units','normalized','Position',[0.04,1-5*dy3-4*dy03-dy13,dx3,dy3]);
set(handles.chblabel,'String','Подписывать уровень');
set(handles.chblabel,'FontName',fonttype.buttons,'FontSize',fontsize.buttons,'Visible','off');
set(handles.chbTrace,'Units','normalized','Position',[0.04,1-5*dy3-4*dy03-dy13,dx3,dy3]);
set(handles.chbTrace,'String','Учет трассы');
set(handles.chbTrace,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.chbAutoLevel,'Units','normalized','Position',[0.04,1-6*dy3-5*dy03-dy13,dx3,dy3]);
set(handles.chbAutoLevel,'String','Авто уровень сечения');
set(handles.chbAutoLevel,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);

%---------------------------INIT---------------------------------------
handles=ChZadacha(handles);
end