function handles=StartUpFcnKlaster(handles)
uipanelwidth=0.98;
uipanelheight=0.94;
uipanelx=0.01;
uipanely=0.01;
togglebwidth=0.1;
togglebheight=0.05;
fonttype.buttons=handles.preferences.fonttype.buttons;
fonttype.subpanel=handles.preferences.fonttype.subpanel;
fonttype.axes=handles.preferences.fonttype.axes;
fonttype.text=handles.preferences.fonttype.text;
fonttype.matrix=handles.preferences.fonttype.matrix;
fontsize.buttons=handles.preferences.fontsize.buttons;
fontsize.subpanel=handles.preferences.fontsize.subpanel;
fontsize.axes=handles.preferences.fontsize.axes;
fontsize.text=handles.preferences.fontsize.text;
fontsize.matrix=handles.preferences.fontsize.matrix;
%||-----------------------uipklaster-------------------------------------
set(handles.uipklaster,'Units','normalized','Position',[uipanelx,uipanely,uipanelwidth,uipanelheight]);
set(handles.uipklaster,'BackgroundColor',handles.preferences.color.panel);
set(handles.uipklaster,'Title','Кластер','TitlePosition','righttop');
set(handles.uipklaster,'FontName',fonttype.subpanel,'FontSize',fontsize.subpanel);
%|||----------------------tbklaster--------------------------------
set(handles.tbklaster,'BackgroundColor',handles.preferences.color.tabs(1,:));
set(handles.tbklaster,'Units','normalized','Position',[0.11,0.95,togglebwidth,togglebheight]);
set(handles.tbklaster,'String','Кластер');
set(handles.tbklaster,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
%|||----------------------uipgeneration---------------------------------
set(handles.uipgeneration,'Units','normalized','Position',[0.01,0.01,0.98,0.23]);
set(handles.uipgeneration,'BackgroundColor',handles.preferences.color.subpanel);
set(handles.uipgeneration,'Title','Автоматическое создание');
set(handles.uipgeneration,'FontName',fonttype.subpanel,'FontSize',fontsize.subpanel);
uipgendx=0.485;uipgendy=0.7;uipgenX1=0.01;uipgenX2=0.505;uipgenY=0.3;
butgendx=0.15;butgendy=0.25;
tX1=0.05;tX2=0.5;tY1=0.1;tY2=0.5;tdx=0.3;tdy=0.4;
eddx=0.12;eddy=0.4;
%||||----------------------uipgeks-------------------------------------
set(handles.uipgeks,'Units','normalized','Position',[uipgenX1,uipgenY,uipgendx,uipgendy]);
set(handles.uipgeks,'BackgroundColor',handles.preferences.color.subpanel);
set(handles.uipgeks,'Title','Гексагональная структура');
set(handles.uipgeks,'FontName',fonttype.subpanel,'FontSize',fontsize.subpanel);
set(handles.pbgeksgen,'Units','normalized','Position',[uipgenX1+uipgendx-butgendx,uipgenY-butgendy,butgendx,butgendy]);
set(handles.pbgeksgen,'String','Создать структуру');
set(handles.pbgeksgen,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.text15,'Units','normalized','Position',[tX1,tY2,tdx,tdy]);
set(handles.text15,'String','Число этажей','HorizontalAlignment','left');
set(handles.text15,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.text16,'Units','normalized','Position',[tX1,tY1,tdx,tdy]);
set(handles.text16,'String','Число излучателей в центральном этаже','HorizontalAlignment','left');
set(handles.text16,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.text17,'Units','normalized','Position',[tX2,tY2,tdx,tdy]);
set(handles.text17,'String','Горизонтальное смещение','HorizontalAlignment','left');
set(handles.text17,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.text18,'Units','normalized','Position',[tX2,tY1,tdx,tdy]);
set(handles.text18,'String','Вертикальное смещение','HorizontalAlignment','left');
set(handles.text18,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.edgeksNet,'Units','normalized','Position',[tX1+tdx,tY2,eddx,eddy],'String','');
set(handles.edgeksNet,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.edgeksNcentr,'Units','normalized','Position',[tX1+tdx,tY1,eddx,eddy],'String','');
set(handles.edgeksNcentr,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.edgeksdx,'Units','normalized','Position',[tX2+tdx,tY2,eddx,eddy],'String','');
set(handles.edgeksdx,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.edgeksdy,'Units','normalized','Position',[tX2+tdx,tY1,eddx,eddy],'String','');
set(handles.edgeksdy,'FontName',fonttype.text,'FontSize',fontsize.text);
%||||----------------------uiporto-------------------------------------
set(handles.uiporto,'Units','normalized','Position',[uipgenX2,uipgenY,uipgendx,uipgendy]);
set(handles.uiporto,'BackgroundColor',handles.preferences.color.subpanel);
set(handles.uiporto,'Title','Прямоугольная структура');
set(handles.uiporto,'FontName',fonttype.subpanel,'FontSize',fontsize.subpanel);
set(handles.pbortogen,'Units','normalized','Position',[uipgenX2+uipgendx-butgendx,uipgenY-butgendy,butgendx,butgendy]);
set(handles.pbortogen,'String','Создать структуру');
set(handles.pbortogen,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.text19,'Units','normalized','Position',[tX1,tY2,tdx,tdy]);
set(handles.text19,'String','Число этажей','HorizontalAlignment','left');
set(handles.text19,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.text20,'Units','normalized','Position',[tX1,tY1,tdx,tdy]);
set(handles.text20,'String','Число излучателей в этаже','HorizontalAlignment','left');
set(handles.text20,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.text21,'Units','normalized','Position',[tX2,tY2,tdx,tdy]);
set(handles.text21,'String','Горизонтальное смещение','HorizontalAlignment','left');
set(handles.text21,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.text22,'Units','normalized','Position',[tX2,tY1,tdx,tdy]);
set(handles.text22,'String','Вертикальное смещение','HorizontalAlignment','left');
set(handles.text22,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.edortoNet,'Units','normalized','Position',[tX1+tdx,tY2,eddx,eddy],'String','');
set(handles.edortoNet,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.edortoNoblet,'Units','normalized','Position',[tX1+tdx,tY1,eddx,eddy],'String','');
set(handles.edortoNoblet,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.edortodx,'Units','normalized','Position',[tX2+tdx,tY2,eddx,eddy],'String','');
set(handles.edortodx,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.edortody,'Units','normalized','Position',[tX2+tdx,tY1,eddx,eddy],'String','');
set(handles.edortody,'FontName',fonttype.text,'FontSize',fontsize.text);
%|||----------------------uipkledit---------------------------------
set(handles.uipkledit,'Units','normalized','Position',[0.55,0.25,0.44,0.74]);
set(handles.uipkledit,'BackgroundColor',handles.preferences.color.subpanel);
set(handles.uipkledit,'Title','Правка структуры');
set(handles.uipkledit,'FontName',fonttype.subpanel,'FontSize',fontsize.subpanel);
%||||----------------------elements---------------------------------
set(handles.uitkledit,'Units','normalized','Position',[0.02,0.02,0.635,0.9]);
datax=[];
datay=[];
datadel=[];
set(handles.uitkledit,'Data',[datax' datay' datadel'],'ColumnName',{'позиция X','позиция Y','Удалить'});
set(handles.uitkledit,'ColumnEditable',logical([1 1 1]));
set(handles.uitkledit,'FontName',fonttype.matrix,'FontSize',fontsize.matrix);
set(handles.tNobl,'Units','normalized','Position',[0.02,0.93,0.3,0.05]);
set(handles.tNobl,'String','Число облучателей','HorizontalAlignment','left');
set(handles.tNobl,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.pbsortkl,'Units','normalized','Position',[0.68,0.85,0.3,0.07]);
set(handles.pbsortkl,'String','Отсортировать');
set(handles.pbsortkl,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.pbaddobl,'Units','normalized','Position',[0.68,0.75,0.3,0.07]);
set(handles.pbaddobl,'String','Добавить излучатель');
set(handles.pbaddobl,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.text24,'Units','normalized','Position',[0.68,0.65,0.1,0.04],'String','X:');
set(handles.text24,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.edaddX,'Units','normalized','Position',[0.78,0.65,0.2,0.07],'String','');
set(handles.edaddX,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.text25,'Units','normalized','Position',[0.68,0.55,0.1,0.04],'String','Y:');
set(handles.text25,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.edaddY,'Units','normalized','Position',[0.78,0.55,0.2,0.07],'String','');
set(handles.edaddY,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.pbdelmanyobl,'Units','normalized','Position',[0.68,0.25,0.3,0.07]);
set(handles.pbdelmanyobl,'String','Удалить несколько');
set(handles.pbdelmanyobl,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.pbdelobl,'Units','normalized','Position',[0.68,0.45,0.3,0.07]);
set(handles.pbdelobl,'String','Удалить узлучатель');
set(handles.pbdelobl,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.text26,'Units','normalized','Position',[0.68,0.35,0.1,0.04],'String','№');
set(handles.text26,'FontName',fonttype.text,'FontSize',fontsize.text);
set(handles.eddeloblN,'Units','normalized','Position',[0.78,0.35,0.2,0.07],'String','');
set(handles.eddeloblN,'FontName',fonttype.text,'FontSize',fontsize.text);
%|||----------------------uipvidklastera---------------------------------
set(handles.uipvidklastera,'Units','normalized','Position',[0.01,0.25,0.53,0.6]);
set(handles.uipvidklastera,'BackgroundColor',handles.preferences.color.subpanel);
set(handles.uipvidklastera,'Title','Общий вид кластера');
set(handles.uipvidklastera,'FontName',fonttype.subpanel,'FontSize',fontsize.subpanel);
set(handles.axklaster,'Units','normalized','Position',[0.08,0.1,0.87,0.85]);
set(handles.axklaster,'FontName',fonttype.axes,'FontSize',fontsize.axes);
%axes(handles.axklaster);
%box on;
%||||----------------------buttons--------------------------------------
set(handles.pbopenkl,'Units','normalized','Position',[0.01,0.86,0.15,0.05]);
set(handles.pbopenkl,'String','Открыть структуру');
set(handles.pbopenkl,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.pbsavekl,'Units','normalized','Position',[0.01,0.93,0.15,0.05]);
set(handles.pbsavekl,'String','Сохранить Структуру');
set(handles.pbsavekl,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
set(handles.pbclearkl,'Units','normalized','Position',[0.39,0.86,0.15,0.05]);
set(handles.pbclearkl,'String','Очистить');
set(handles.pbclearkl,'FontName',fonttype.buttons,'FontSize',fontsize.buttons);
end